title: Constantly Learning
subtitle: 'Programming, Information Security, Startups, and Learnings.'
permalink: /:categories/:title
markdown: rdiscount
paginate: 10
paginate_path: "/blog/page:num/"
gems:
  - jekyll-paginate
sass:
  style: :compressed
exclude:
  - Rakefile
  - spec/*
  - CNAME
  - vendor
  - "*.sublime-project"
  - node_modules/*
  - bower_components/*
  - tasks/*
  - Gemfile*
  - bower.json
  - README.md
  - specs/*
  - lib/*
