#!/usr/bin/env bash
set -e # halt script on error

bundle exec rake spec
bundle exec jekyll build
bundle exec htmlproof --check-favicon --external_only ./_site

# --external_only
# --disable-external
# --check-html
# --only-4xx